### ISSUE TITLE
Nested iframe elements cannot be detected

### ISSUE THREAD

**Issue by shawncx** [microsoft/playwright-mcp#106]
[test-htmls.zip](https://github.com/user-attachments/files/19555157/test-htmls.zip)

Here's a simple repro. iframe2 is nested in iframe1. I can fill iframe1 input easily. But iframe2 input cannot be detected by mcp

![Image](https://github.com/user-attachments/assets/e7dfdb55-bad8-4f1f-a37e-19edf35d186e)

**Comment by Skn0tt** [comment]
On `v0.0.9`, it's seeing the iframes just fine. Please check if you're also having this problem on `v0.0.9` - we improved something around iframes in that release. Here's the response it's giving to the LLM in my test with your repro:

---

- Page URL: http://localhost:3000/test
- Page Title: Our Funky HTML Page
- Page Snapshot
```yaml
- text: "Content goes here. name-out:"
- textbox "name-out:" [ref=s1e4]
- iframe [ref=s1e5]:
    - text: "iframe Content goes here. iframe-1:"
    - textbox "iframe-1:" [ref=f1s1e4]
    - iframe [ref=f1s1e5]:
        - text: "iframe-2 Content goes here. iframe-2:"
        - textbox "iframe-2:" [ref=f2s1e4]
```
