### ISSUE TITLE
What are ref attributes attached during browser_snapshot command ?

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright-mcp#198]
```
{}

- Ran code:
```js
// <internal code to capture accessibility snapshot>
```

- Page URL: https://itc.ua/ua/articles/zla-fizyka-chomu-bilsha-chastyna-vsesvitu-zavzhdy-bude-nedosyazhnoyu-dlya-lyudstva/
- Page Title: Зла фізика. Чому більша частина Всесвіту завжди буде недосяжною для людства?
- Page Snapshot
```yaml
- link [ref=s2e6]:
    - /url: https://the-creators.agency/ua/?utm_source=vidget&utm_medium=ITC
    - img [ref=s2e7]
- banner [ref=s2e9]:
    - link "ITC.ua" [ref=s2e13]:
        - /url: https://itc.ua/ua/
        - img "ITC.ua" [ref=s2e14]
    - list [ref=s2e15]:
        - listitem [ref=s2e16]:
            - link "Новини" [ref=s2e17]:
                - /url: https://itc.ua/ua/novini/
        - listitem [ref=s2e18]:
            - link "Огляди" [ref=s2e19]:
                - /url: https://itc.ua/ua/oglyadi/
        - listitem [ref=s2e20]:
            - link "Статті" [ref=s2e21]:
                - /url: https://itc.ua/ua/statti/
        - listitem [ref=s2e22]:
            - link "Дописи" [ref=s2e23]:
                - /url: /ua/blogs/
    - combobox [ref=s2e26]:
        - option "ua" [selected] [ref=s2e27]
        - option "en" [ref=s2e28]
        - option "es" [ref=s2e29]
        - option "ru" [ref=s2e30]
    - text: A B
    - link "Create post" [ref=s2e38]:
        - /url: /ua/blogs-itc/
        - img "Create post" [ref=s2e39]
    - link "Увійти" [ref=s2e41]:
        - /url: /ua/blogs-itc/
    - list [ref=s2e44]:
        - listitem [ref=s2e45]:
            - link "Україна" [ref=s2e46]:
                - /url: https://itc.ua/ua/ukrayina/
        - listitem [ref=s2e47]:
            - link "Технології" [ref=s2e48]:
                - /url: https://itc.ua/ua/tehnologiyi/
        - listitem [ref=s2e49]:
            - link "Наука/Космос" [ref=s2e50]:
                - /url: https://itc.ua/ua/nauka-ta-kosmos/
        - listitem [ref=s2e51]:
            - link "Крипто" [ref=s2e52]:
                - /url: https://itc.ua/ua/blokcheyn/
        - listitem [ref=s2e53]:
            - link "IT-бізнес" [ref=s2e54]:
                - /url: https://itc.ua/ua/biznes-ua/
        - listitem [ref=s2e55]:
            - link "Пристрої" [ref=s2e56]:
                - /url: https://itc.ua/ua/pristroyi/
        - listitem [ref=s2e57]:
            - link "Софт" [ref=s2e58]:
                - /url: https://itc.ua/ua/soft/
        - listitem [ref=s2e59]:
            - link "Military Tech" [ref=s2e60]:
                - /url: https://itc.ua/ua/military-tech/
        - listitem [ref=s2e61]:
            - link "Авто" [ref=s2e62]:
                - /url: https://itc.ua/ua/avto-ua/
        - listitem [ref=s2e63]:
            - link "Ігри" [ref=s2e64]:
                - /url: https://itc.ua/ua/igri/
        - listitem [ref=s2e65]:
            - link "Кіно" [ref=s2e66]:
                - /url: https://itc.ua/ua/kino/
        - listitem [ref=s2e67]:
            - link "WTF" [ref=s2e68]:
                - /url: https://itc.ua/ua/wtf-ua/
        - listitem [ref=s2e69]:
            - link "Спецпроєкти" [ref=s2e70]:
                - /url: https://itc.ua/ua/partnerskij-proekt/
    - img "search icon" [ref=s2e73]
- link "Наука та космос" [ref=s2e79]:
    - /url: https://itc.ua/ua/nauka-ta-kosmos/
- text: 16.04.2025 о 14:00
- link "comment 4" [ref=s2e82]:
    - /url: "#itc-comments"
    - img "comment" [ref=s2e83]
    - text: "4"
- img "views icon" [ref=s2e86]
- text: "157"
- heading "Зла фізика. Чому більша частина Всесвіту завжди буде недосяжною для
  людства?" [level=1] [ref=s2e88]
- link "author avatar" [ref=s2e93]:
    - /url: https://itc.ua/ua/author/oleksandr-fedotkin/
    - img "author avatar" [ref=s2e94]
- paragraph [ref=s2e96]:
    - link "Олександр Федоткін" [ref=s2e97]:
        - /url: https://itc.ua/ua/author/oleksandr-fedotkin/
- paragraph [ref=s2e98]: Автор новин та статей
- main [ref=s2e100]:
    - article [ref=s2e101]:
        - figure "pxhere.com" [ref=s2e104]:
            - link "Зла фізика. Чому більша частина Всесвіту завжди буде недосяжною для людства?" [ref=s2e105]:
                - /url: https://itc.ua/wp-content/uploads/2025/04/silhouette-night-star-milky-way-atmosphere-galaxy-113640-pxhere.com_-scaled.jpg
                - img "Зла фізика. Чому більша частина Всесвіту завжди буде
                  недосяжною для людства?" [ref=s2e106]
            - text: pxhere.com
        - paragraph [ref=s2e108]: З того часу, як видатний астрофізик Едвін Габбл у
            середині 20-х років минулого століття відкрив, що Всесвіт не
            статичний, а постійно розширюється, а об’єкти, чиє світло доходить
            до нас, постійно від нас віддаляються, це стало однією з центральних
            тем для сучасної науки.
        - paragraph [ref=s2e114]: У 1998 році два незалежні проєкти — Supernova Cosmology
            Project і High-Z Supernova Search Team виявили, що Всесвіт
            розширюється з прискоренням. Для цього вони тривалий час
            спостерігали за одним й тим самим об’єктом. Результати спостережень
            за далекими галактиками підтвердили, що вони віддаляються. Була
            виміряна швидкість їхнього руху. Через деякий час астрофізики
            повернулись до спостереження за цими об’єктами і зафіксували, що
            вони стали віддалятись ще швидше.
        - paragraph [ref=s2e116]: Але як саме відбувається це розширення? Астрофізики
            часто кажуть, що віддалені від нас регіони Всесвіту продовжують
            віддалятись із надсвітловою швидкістю. Але чи означає це, що якісь
            об’єкти у космосі здатні порушити один з ключових принципів
            сформульованої Альбертом Ейнштейном Спеціальної теорії відносності
            щодо того, що жоден об’єкт у Всесвіті не може перевищити швидкість
            світла.
        - figure "NASA" [ref=s2e117]:
            - link "Зла фізика. Більша частина Всесвіту завжди буде недосяжною для людства" [ref=s2e118]:
                - /url: https://itc.ua/wp-content/uploads/2025/04/CMB_Timeline300_no_WMAP-scaled.jpg
                - img "Зла фізика. Більша частина Всесвіту завжди буде
                  недосяжною для людства" [ref=s2e119]
            - text: NASA
        - paragraph [ref=s2e121]: Так, частинки, що не мають маси, у вакуумі можуть
            рухатись зі швидкістю світла. Тоді як всі інші об’єкти з певною
            масою де інде, або ті ж частинки без маси, однак у певному
            середовищі, завжди рухатимуться зі швидкістю, нижчою за швидкість
            світла.
        - paragraph [ref=s2e122]: За оцінками астрофізиків, вік Всесвіту складає близько
            13,8 млрд років. Наразі науковці вже можуть виміряти не тільки
            нинішню швидкість розширення Всесвіту, а й те, якою вона була у
            далекому минулому та в усі проміжні періоди. До прикладу, світло від
            об’єкта, що перебував на відстані 100 метрів від нас на момент
            Великого вибуху, дісталось б до нас лише через 13,8 млрд років, тоді
            як сам об’єкт вже перебував би на відстані у понад 46 млрд світлових
            років.
        - paragraph [ref=s2e128]:
            - iframe [ref=s2e130]:
                - link "Photo image of The Science Asylum" [ref=f1s2e10]
                - link "How do we know the Universe is expanding?" [ref=f1s2e13]:
                    - /url: https://www.youtube.com/watch?v=LE_wbOw39Mk
                - button "Share" [ref=f1s2e16]:
                    - img [ref=f1s2e18]
                    - text: Share
                - button "Play" [ref=f1s2e24]:
                    - img [ref=f1s2e25]
                - link "Watch on YouTube" [ref=f1s2e31]:
                    - /url: https://www.youtube.com/watch?v=LE_wbOw39Mk&embeds_referring_euri=https%3A%2F%2Fitc.ua%2F
        - paragraph [ref=s2e131]: Але чи означає це, що простір розширився із надсвітловою
            швидкістю? Власне, ні, адже розширення Всесвіту не відбувається із
            якоюсь конкретною швидкістю, а скоріше з відповідним ступенем, що
            вимірюється у швидкості на одиницю відстані. Зазвичай це розширення
            вимірюють у кілометрах в секунду на мегапарсек (км/(с·Мпк)), де
            мегапарсек — це близько 3,26 млн світлових років. У такому разі,
            якщо швидкість розширення складає 70 км/с/Мпк, то об’єкт на відстані
            5 Мпк віддаляється відносно нас зі швидкістю 350 км/с, 100 Мпк — зі
            швидкістю 7 тис. км/с, а у випадку з об’єктом, розташованим на
            відстані 10 тис. Мпк, нам здаватиметься, що він віддаляється зі
            швидкістю у 700 тис. км/с.
        - complementary [ref=s2e132]:
            - text: Реклама Creators - Агенція з міжнародного PR для технологічних та B2B
                компаній
            - img [ref=s2e136]
            - img [ref=s2e140]
            - text: PR для компаній та їх лідерів
            - img [ref=s2e143]
            - text: Організація інтерв’ю в медіа, подкастах, виступи на конференціях
            - img [ref=s2e146]
            - text: Європа, Азія, Америка
            - link "Дізнатись деталі" [ref=s2e149]:
                - /url: https://the-creators.agency/ua/?utm_source=vidget&utm_medium=ITC
                - text: Дізнатись деталі
                - img [ref=s2e150]
        - paragraph [ref=s2e152]: З цього не витікає, що якісь об’єкти можуть рухатись із
            надсвітловою швидкістю. Спеціальна теорія відносності постулює, що
            два об’єкти в одному просторово-часовому відрізку, тобто, які
            займають один і той же простір в один і той самий час, не можуть
            рухатись один відносно одного з надсвітловою швидкістю. Навіть як
            один з них рухатиметься на північ зі швидкістю 99% від швидкості
            світла, а другий — на південь із тією самою швидкістю, їхня
            швидкість не буде дорівнювати 198% швидкості світла відносно одне
            одного, а буде дорівнювати 99,995% швидкості світла. І це не
            важливо, як швидко рухатиметься кожен з них, вони ніколи не зможуть
            перевищити швидкість світла відносно один одного.
        - paragraph [ref=s2e153]: Це і є те, що називають відносністю. Вона вимірює
            відносний рух між двома об’єктами в одній точці простору-часу. Однак
            Спеціальна теорія відносності описує правила для статичного
            простору, що не розширюється, і лише випадки прямолінійного,
            рівномірного руху.
        - paragraph [ref=s2e159]: Водночас Загальна теорія відносності вже містить факт
            розширення простору та усі нелінійні випадки руху. Вимірявши
            кількість звичайної (баріонної) матерії, темної матерії, темної
            енергії, нейтрино, випромінення та світла, яке надходить до нас з
            різних кінців видимого Всесвіту, зміщуючись у червоний спектр
            внаслідок розширення простору, науковці можуть відтворити розміри
            Всесвіту у будь-який момент минулого.
        - figure "RASC Calgary Centre" [ref=s2e160]:
            - link "Зла фізика. Більша частина Всесвіту завжди буде недосяжною для людства" [ref=s2e161]:
                - /url: https://itc.ua/wp-content/uploads/2025/04/redshifts.gif
                - img "Зла фізика. Більша частина Всесвіту завжди буде
                  недосяжною для людства" [ref=s2e162]
            - text: RASC Calgary Centre
        - paragraph [ref=s2e164]: Вже за секунду після Великого вибуху розміри Всесвіту
            складали 10 світлових років, а через рік — 100 тис. світлових років.
            Однак ніколи жодна частинка при цьому не рухалась з надсвітловою
            швидкістю відносно іншої.
        - paragraph [ref=s2e165]: Розширювався сам простір між частинками, відстань між
            ними збільшувалась, а довжина хвилі у просторі розтягувалась. І все
            це тривало мільярди років і триває зараз, та навіть з прискоренням.
            Навіть якщо ми будемо рухатись зі швидкістю світла, ми ніколи не
            досягнемо об’єктів, що перебувають від нас на відстані далі 15,6
            млрд світлових років, оскільки сам простір між об’єктами продовжує
            розширюватись. На думку багатьох фізиків, рушійною силою цього
            розширення є саме енергія вакууму, яка ніби розштовхує простір та
            прискорює галактики, що віддаляються від нас.
        - text: Спецпроєкти
        - link [ref=s2e172]:
            - /url: https://itc.ua/ua/articles/video-audio-ta-knopky-oplaty-yak-rozsylky-rcs-povidomlen-vid-telescope-zminyat-robotu-z-kliyentamy/
        - 'link "Відео, аудіо та кнопки оплати: як розсилки RCS-повідомлень від Telescope змінять роботу з клієнтами" [ref=s2e173]':
            - /url: https://itc.ua/ua/articles/video-audio-ta-knopky-oplaty-yak-rozsylky-rcs-povidomlen-vid-telescope-zminyat-robotu-z-kliyentamy/
        - link [ref=s2e177]:
            - /url: https://itc.ua/ua/articles/schneider-electric-zabezpechyla-merezhu-azk-okko-obladnannyam-dlya-bezperebijnogo-elektropostachannya-za-bud-yakyh-umov/
        - link "Schneider Electric забезпечила мережу АЗК ОККО обладнанням для безперебійного електропостачання за будь-яких умов" [ref=s2e178]:
            - /url: https://itc.ua/ua/articles/schneider-electric-zabezpechyla-merezhu-azk-okko-obladnannyam-dlya-bezperebijnogo-elektropostachannya-za-bud-yakyh-umov/
        - paragraph [ref=s2e179]: Ми ніколи не зможемо дістатись більшої частини Всесвіту.
        - paragraph [ref=s2e180]: Чим далі знаходиться об’єкт спостереження, тим більше
            він зміщуватиметься у червоний спектр і тим сильніше здаватиметься,
            що він віддаляється все швидше і швидше відносно вас. Відносно
            спостерігача ніщо не рухається швидше за світло і це справедливо для
            будь-якого місця у Всесвіті у будь-який момент часу.
        - figure "Infrared Science Archive" [ref=s2e181]:
            - link "Зла фізика. Більша частина Всесвіту завжди буде недосяжною для людства" [ref=s2e182]:
                - /url: https://itc.ua/wp-content/uploads/2025/04/2MASS_LSS_chart-NEW_Nasa.jpg
                - img "Зла фізика. Більша частина Всесвіту завжди буде
                  недосяжною для людства" [ref=s2e183]
            - text: Infrared Science Archive
        - paragraph [ref=s2e185]: Чим далі астрономи заглядають у космічний простір, тим
            швидше ці галактики та галактичні скупчення віддаляються. І на
            великих відстанях — можна бачити, що чим далі вони від нас, то
            швидше вони віддалятимуться, що і відображене у законі Габбла.
        - paragraph [ref=s2e186]: Це також означає, що існують настільки віддалені від нас
            області Всесвіту, що світлове випромінювання звідти ніколи до нас не
            дістанеться. Зокрема, це ті частини Всесвіту, які перебувають від
            нас на відстані 46,1 млрд світлових років. Таким чином будь-який
            об’єкт на відстані 15,6 млрд світлових років від нас стає навічно
            недосяжним. А це близько 95% обсягу видимої нам частини Всесвіту.
        - paragraph [ref=s2e192]: Якби людство прямо зараз почало досліджувати космос,
            рухаючись зі швидкістю світла, воно змогло б досягти всіх галактик у
            цих межах. Однак це не більше 4-5% від поточного видимого Всесвіту.
            Щороку близько 160 млрд зірок, яких вистачить для утворення однієї
            невеликої галактики, віддаляються від Землі на недосяжну відстань.
        - link "Всесвіт" [ref=s2e198]:
            - /url: https://itc.ua/ua/tag/vsesvit/
        - text: ","
        - link "Космос" [ref=s2e200]:
            - /url: https://itc.ua/ua/tag/kosmos-ua/
        - text: ","
        - link "Наука та космос" [ref=s2e202]:
            - /url: https://itc.ua/ua/tag/nauka-ta-kosmos/
        - text: ","
        - link "розширення Всесвіту" [ref=s2e204]:
            - /url: https://itc.ua/ua/tag/rozshyrennya-vsesvitu/
        - text: ","
        - link "світло" [ref=s2e206]:
            - /url: https://itc.ua/ua/tag/svitlo/
        - text: ","
        - link "Теорія відносності" [ref=s2e208]:
            - /url: https://itc.ua/ua/tag/teoriya-vidnosnosti/
        - text: ","
        - link "Фізика" [ref=s2e210]:
            - /url: https://itc.ua/ua/tag/fizyka/
        - text: ","
        - link "Швидкість світла" [ref=s2e212]:
            - /url: https://itc.ua/ua/tag/shvydkist-svitla/
    - heading "Популярні статі" [level=3] [ref=s2e214]
    - link [ref=s2e218]:
        - /url: https://itc.ua/ua/articles/oglyad-arhitektury-amd-rdna-4-chervonyj-udar/
    - 'link "Огляд архітектури AMD RDNA 4: червоний удар" [ref=s2e219]':
        - /url: https://itc.ua/ua/articles/oglyad-arhitektury-amd-rdna-4-chervonyj-udar/
    - link [ref=s2e222]:
        - /url: https://itc.ua/ua/articles/oglyad-smartkiltsya-imiki-ring-rozumnyj-minimalizm-na-paltsi/
    - 'link "Огляд смарткільця IMIKI Ring: розумний мінімалізм на пальці" [ref=s2e223]':
        - /url: https://itc.ua/ua/articles/oglyad-smartkiltsya-imiki-ring-rozumnyj-minimalizm-na-paltsi/
    - link [ref=s2e226]:
        - /url: https://itc.ua/ua/articles/narodnyj-pk-misyatsya-kviten-2025/
    - link "Народний ПК місяця (Квітень 2025)" [ref=s2e227]:
        - /url: https://itc.ua/ua/articles/narodnyj-pk-misyatsya-kviten-2025/
    - complementary [ref=s2e234]:
        - text: ЕКСПЕРТНА ДУМКА
        - img [ref=s2e238]
        - img "ITC.ua" [ref=s2e240]
        - img [ref=s2e249]
        - text: Написати
        - link "Не підтримую 0" [ref=s2e254]:
            - /url: /ua/longcomment/?post=3176682
        - img [ref=s2e258]
        - link "Підтримую 0" [ref=s2e260]:
            - /url: /ua/longcomment/?post=3176682
        - img [ref=s2e264]
    - text: "Що думаєте про цю статтю? Голосів: 4"
    - img "Файно є" [ref=s2e276]
    - text: 3 Файно є
    - img "Йой, най буде!" [ref=s2e284]
    - text: 0 Йой, най буде!
    - img "Трясця!" [ref=s2e292]
    - text: 1 Трясця!
    - img "Ну такої..." [ref=s2e300]
    - text: 0 Ну такої...
    - img "Бісить, аж тіпає!" [ref=s2e308]
    - text: 0 Бісить, аж тіпає! Loading comments...
- complementary [ref=s2e319]:
    - list [ref=s2e320]:
        - listitem [ref=s2e321]
        - listitem [ref=s2e325]
        - listitem [ref=s2e327]:
            - heading "Найобговорюваніше" [level=3] [ref=s2e328]
            - text: b 197
            - link [ref=s2e335]:
                - /url: https://itc.ua/ua/novini/zaplatyat-usi-getmantsev-pro-novi-podatky-na-dohody-otrymani-cherez-internet-prynesut-10-mlrd-grn-shhoroku/
            - 'link "«Заплатять усі»: Гетманцев про нові податки на доходи, отримані через інтернет — принесуть 10 млрд грн щороку" [ref=s2e337]':
                - /url: https://itc.ua/ua/novini/zaplatyat-usi-getmantsev-pro-novi-podatky-na-dohody-otrymani-cherez-internet-prynesut-10-mlrd-grn-shhoroku/
            - text: b 88
            - link [ref=s2e345]:
                - /url: https://itc.ua/ua/novini/uryad-planuye-styaguvaty-podatky-z-kozhnogo-prodazhu-cherez-olx-rozetka-ta-prom-zakonoproyekt/
            - link "Уряд планує стягувати податки з кожного продажу через OLX, Rozetka та Prom — законопроєкт" [ref=s2e347]:
                - /url: https://itc.ua/ua/novini/uryad-planuye-styaguvaty-podatky-z-kozhnogo-prodazhu-cherez-olx-rozetka-ta-prom-zakonoproyekt/
            - text: b 88
            - link [ref=s2e355]:
                - /url: https://itc.ua/ua/articles/oglyad-msi-geforce-rtx-5070-12g-gaming-trio-oc-bytva-za-serednij-segment/
            - 'link "Огляд MSI GeForce RTX 5070 12G GAMING TRIO OC: битва за середній сегмент" [ref=s2e357]':
                - /url: https://itc.ua/ua/articles/oglyad-msi-geforce-rtx-5070-12g-gaming-trio-oc-bytva-za-serednij-segment/
            - text: b 74
            - link [ref=s2e365]:
                - /url: https://itc.ua/ua/articles/oglyad-2e-eb19-elektrobajk-bez-pafosu-ale-z-harakterom/
            - 'link "Огляд 2E EB19: електробайк без пафосу, але з характером" [ref=s2e367]':
                - /url: https://itc.ua/ua/articles/oglyad-2e-eb19-elektrobajk-bez-pafosu-ale-z-harakterom/
            - text: b 83
            - link [ref=s2e375]:
                - /url: https://itc.ua/ua/novini/min-yust-zablokuvav-rahunky-26-tysyacham-ukrayintsiv-za-nesplatu-shtrafiv-ttsk/
            - link "Мін’юст заблокував рахунки 26 тисячам українців за несплату штрафів ТЦК" [ref=s2e377]:
                - /url: https://itc.ua/ua/novini/min-yust-zablokuvav-rahunky-26-tysyacham-ukrayintsiv-za-nesplatu-shtrafiv-ttsk/
        - listitem [ref=s2e379]
        - listitem [ref=s2e382]:
            - heading "Партнерські блоги" [level=3] [ref=s2e385]
            - link "logo acer Acer Україна" [ref=s2e387]:
                - /url: https://itc.ua/ua/author/acer-ukraine/
                - img "logo acer" [ref=s2e388]
                - paragraph [ref=s2e389]: Acer Україна
            - link "logo devicelabs DeviceLabs" [ref=s2e390]:
                - /url: https://itc.ua/ua/author/devicelabs/
                - img "logo devicelabs" [ref=s2e391]
                - paragraph [ref=s2e392]: DeviceLabs
            - link "logo iCases iCases.ua" [ref=s2e393]:
                - /url: https://itc.ua/ua/author/icases-ua/
                - img "logo iCases" [ref=s2e394]
                - paragraph [ref=s2e395]: iCases.ua
        - listitem [ref=s2e396]
        - listitem [ref=s2e401]:
            - heading "Вибір редакції" [level=3] [ref=s2e402]
            - paragraph [ref=s2e405]:
                - 'link "Забудьте про «напругу Габбла»: оберт Всесвіту раз на 500 млрд років пояснює найбільшу загадку космології" [ref=s2e406]':
                    - /url: https://itc.ua/ua/novini/zabudte-pro-naprugu-gabbla-obert-vsesvitu-raz-na-500-mlrd-rokiv-poyasnyuye-najbilshu-zagadku-kosmologiyi/
            - link "comment 0" [ref=s2e408]:
                - /url: "#itc-comments"
                - img "comment" [ref=s2e409]
                - text: "0"
            - paragraph [ref=s2e412]:
                - link "Місцеві адміністрації Китаю продають конфісковану криптовалюту попри чинну заборону" [ref=s2e413]:
                    - /url: https://itc.ua/ua/novini/mistsevi-administratsiyi-kytayu-prodayut-konfiskovanu-kryptovalyutu-popry-chynnu-zaboronu/
            - link "comment 0" [ref=s2e415]:
                - /url: "#itc-comments"
                - img "comment" [ref=s2e416]
                - text: "0"
            - paragraph [ref=s2e419]:
                - link "Трамп запустить схожу на «Монополію» криптогру з NFT" [ref=s2e420]:
                    - /url: https://itc.ua/ua/novini/tramp-zapustyt-shozhu-na-monopoliyu-kryptogru-z-nft/
            - link "comment 3" [ref=s2e422]:
                - /url: "#itc-comments"
                - img "comment" [ref=s2e423]
                - text: "3"
            - paragraph [ref=s2e426]:
                - link "Відеоогляд ноутбука Acer Aspire 15 (A15-41M) — потужність та універсальність AMD" [ref=s2e427]:
                    - /url: https://itc.ua/ua/novini/videooglyad-noutbuka-acer-aspire-15-a15-41m-potuzhnist-ta-universalnist-amd/
            - link "comment" [ref=s2e429]:
                - /url: "#itc-comments"
                - img "comment" [ref=s2e430]
            - paragraph [ref=s2e433]:
                - link "Game Pass отримає ще 12 ігор у квітні — Clair Obscur, Far Cry 4 та повернення GTA 5" [ref=s2e434]:
                    - /url: https://itc.ua/ua/novini/game-pass-otrymaye-shhe-12-igor-u-kvitni-clair-obscur-far-cry-4-ta-povernennya-gta-5/
            - link "comment 1" [ref=s2e436]:
                - /url: "#itc-comments"
                - img "comment" [ref=s2e437]
                - text: "1"
        - listitem [ref=s2e439]
        - listitem [ref=s2e443]
- contentinfo [ref=s2e445]:
    - link "ITC.ua" [ref=s2e452]:
        - /url: https://itc.ua/ua/
        - img "ITC.ua" [ref=s2e453]
    - list [ref=s2e455]:
        - listitem [ref=s2e456]:
            - link "Про проєкт" [ref=s2e457]:
                - /url: https://itc.ua/ua/o-proekte-itc-ua/
        - listitem [ref=s2e458]:
            - link "Команда ITC" [ref=s2e459]:
                - /url: https://itc.ua/ua/komanda-itc-2/
        - listitem [ref=s2e460]:
            - link "Реклама на сайті" [ref=s2e461]:
                - /url: https://specials.itc.ua/
        - listitem [ref=s2e462]:
            - link "Аукціон відплати" [ref=s2e463]:
                - /url: https://creatorsmediagroup.com/pidtrymka-zahysnykiv-ukrayiny/
        - listitem [ref=s2e464]:
            - link "Відключити рекламу" [ref=s2e465]:
                - /url: https://itc.ua/ua/vidklyuchyty-reklamu/
        - listitem [ref=s2e466]:
            - link "Політики ITC.ua для користувачів, відвідувачів та авторів" [ref=s2e467]:
                - /url: https://itc.ua/ua/polityky-itc-ua/
    - text: © 1993–2025 ITC.ua Ми використовуємо ілюстрації від
    - link "Depositphotos" [ref=s2e472]:
        - /url: https://depositphotos.com/ua/
    - text: "Окремі матеріали можуть містити посилання на партнерів — це не впливає на
        контент та політику редакції. Проте дає виданню можливості для розвитку.
        Контакти: редакція –"
    - link "news@itc.ua" [ref=s2e475]:
        - /url: mailto:news@itc.ua
    - text: ", партнерство та розміщення реклами –"
    - link "specials@itc.ua" [ref=s2e476]:
        - /url: mailto:specials@itc.ua
    - 'link "{" [ref=s2e479]':
        - /url: https://t.me/itcua
    - link "t" [ref=s2e481]:
        - /url: https://twitter.com/ITCUA
    - link "u" [ref=s2e483]:
        - /url: https://www.facebook.com/ITC.UA
    - link "w" [ref=s2e485]:
        - /url: https://www.youtube.com/user/hotlinevideoua
    - link "v" [ref=s2e487]:
        - /url: https://itc.ua/ua/feed/
    - paragraph [ref=s2e493]:
        - text: Підтримка серверів
        - link "indevlab logo" [ref=s2e494]:
            - /url: https://indevlab.com
            - img "indevlab logo" [ref=s2e495]
    - paragraph [ref=s2e497]:
        - text: Партнер по SEO
        - link "netpeak logo" [ref=s2e498]:
            - /url: https://netpeak.ua
            - img "netpeak logo" [ref=s2e499]
- text: Я підтверджую те, що мені 21 рік або більше, і погоджуюсь з
- link "усіма політиками сайту itc.ua" [ref=s2e501]:
    - /url: https://itc.ua/ua/polityky-itc-ua/
- button "Ок" [ref=s2e502]
- status [ref=s2e505]
```

Absolutely everywhere are these [ref=s2e479] with different values. These are not valid aria snapshots. What are these ? How do I capture aria snapshot ?
